### ISSUE TITLE
swarm-bench sometimes panic's

### ISSUE THREAD

**Issue by lazypower** [aluzzardi/swarm-bench#4]
When benchmarking a slew of hosts, the swarm-bench tool has been extremely helpful to determine how "ready" a host is to accept a ton of containers executing a workload.

However i've found it to be rather consistent about one in every five runs yields a panic

panic: API error (500): Container created but refresh didn't report it back

```
goroutine 8 [running]:
panic(0x845400, 0xc82043baa0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.worker(0x14, 0x7ffcc348ff25, 0x6, 0xc82000a140, 0x0, 0x0, 0xc820055c00)
        /go/src/github.com/aluzzardi/swarm-bench/main.go:31 +0x1e9
main.session.func1(0x14, 0x7ffcc348ff25, 0x6, 0xc82000a140, 0x0, 0x0, 0xc820055c00, 0xc820015bf0)
        /go/src/github.com/aluzzardi/swarm-bench/main.go:52 +0x5d
created by main.session
        /go/src/github.com/aluzzardi/swarm-bench/main.go:54 +0x14c
```

This is using the latest version of swarm-bench in master, against a docker-machine provisioned swarm-cluster, and a juju deployed swarm cluster. Both of which are three node swarm clusters, with a single manager.

**Comment by lazypower** [comment]
This looks to be at its root an issue with swarm. xref with https://github.com/docker/swarm/pull/2190
